# Generated by Django 5.1.5 on 2025-02-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaifirstmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
